version: "3.7"
services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"

  api:
    container_name: API
    restart: always
    build: ./backend/
    ports:
      - "5000:5000"
    environment:
      - "DB=mongodb+srv://user1:test1234@sem03pg2.0eybl.mongodb.net/test"
      - NODE_ENV=development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  client:
    container_name: react
    build: ./frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api
