version: "3.7"
services:
  mongo:
    container_name: Database
    image: mongo:latest
  server:
    container_name: Server
    build: backend
    ports:
      - "5000:5000"
    environment:
      - "DB=mongodb+srv://user1:test1234@sem03pg2.0eybl.mongodb.net/test"
      - NODE_ENV=development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  react:
    container_name: React
    build: frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
